Feature/task 425 implement compute quotient for bisimulation class
virtualsatellite/VirtualSatellite4-FDIR pull request #433
Opened 2021-06-02 17:09 UTC by vivekramayanam

Creating a pull request for merging ComputeQuotient Implementation

2021-06-07 08:59 UTC, SaMuellerDLR requested changes
Please clean up whitespaces!

2021-06-07 08:59 UTC, SaMuellerDLR commented on de.dlr.sc.virsat.fdir.core.test/src/de/dlr/sc/virsat/fdir/core/markov/algorithm/BisimulationTest.java
> +        List<Object> stateLabelsS3 = ma.getSuccEvents(s3);
Whitespacing seems off here.

2021-06-07 08:59 UTC, SaMuellerDLR commented on de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/markov/MarkovAutomaton.java
> +
remove blank line

2021-06-07 08:59 UTC, SaMuellerDLR commented on de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/markov/MarkovAutomaton.java
> +
remove blank line

2021-06-07 08:59 UTC, SaMuellerDLR commented on de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/markov/MarkovAutomaton.java
> +
remove blank line

2021-06-07 08:59 UTC, SaMuellerDLR commented on de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/markov/MarkovAutomaton.java
> +
remove blank line

2021-06-07 08:59 UTC, SaMuellerDLR commented on de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/markov/algorithm/Bisimulation.java
> +
remove blank line

2021-06-07 09:37 UTC, vivekramayanam commented on de.dlr.sc.virsat.fdir.core/src/de/dlr/sc/virsat/fdir/core/markov/algorithm/Bisimulation.java
> +
removed

2021-06-10 13:41 UTC, SaMuellerDLR approved these changes
Approved!

2021-06-11 11:32 UTC, merged